Tweak netbird install so it doesn't block the updates. Netbird may not be installed if bug is not fixed!

diff --git a/src/Containerfile b/src/Containerfile
--- a/src/Containerfile
+++ b/src/Containerfile
@@ -144,12 +144,25 @@ RUN --mount=type=cache,dst=/var/cache \
         flatpak \
         kitty kitty-shell-integration kitty-terminfo kamera \
         libappindicator libappindicator-gtk3 \
-        netbird netbird-ui \
+        #netbird netbird-ui \
         plasma-discover-flatpak \
         vlc vlc-plugin-ffmpeg vlc-plugin-pipewire vlc-plugins-extra \
         #waydroid \
         xdg-terminal-exec xdg-user-dirs \
         --allowerasing && \
+    ostree container commit
+
+# Setup Netbird DNF install failed due to post scriptlet bug.
+RUN --mount=type=cache,dst=/var/cache \
+    --mount=type=cache,dst=/var/log \
+    --mount=type=cache,dst=/var/roothome \
+    --mount=type=tmpfs,dst=/tmp \
+    set -euo pipefail && \
+    echo -e " \e[1;34m${IMAGE_NAME}\e[0m  Install \e[36mNetbird\e[0m" && \
+    dnf5 -y --quiet --setopt=keepcache=1 --setopt=install_weak_deps=False \
+    install \
+    netbird netbird-ui \
+    --allowerasing || true && \
     ostree container commit
 
 # Setup Wine (For Affinity Suite)
